# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CaesarCipher(object):
    def setupUi(self, CaesarCipher):
        CaesarCipher.setObjectName("CaesarCipher")
        CaesarCipher.resize(600, 519)
        self.label = QtWidgets.QLabel(CaesarCipher)
        self.label.setGeometry(QtCore.QRect(160, 20, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(CaesarCipher)
        self.label_2.setGeometry(QtCore.QRect(30, 130, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(CaesarCipher)
        self.label_3.setGeometry(QtCore.QRect(50, 240, 55, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.txt_plain_text = QtWidgets.QPlainTextEdit(CaesarCipher)
        self.txt_plain_text.setGeometry(QtCore.QRect(140, 100, 371, 111))
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.txt_key = QtWidgets.QPlainTextEdit(CaesarCipher)
        self.txt_key.setGeometry(QtCore.QRect(140, 240, 371, 41))
        self.txt_key.setObjectName("txt_key")
        self.txt_cipher_text = QtWidgets.QPlainTextEdit(CaesarCipher)
        self.txt_cipher_text.setGeometry(QtCore.QRect(140, 310, 371, 91))
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.label_4 = QtWidgets.QLabel(CaesarCipher)
        self.label_4.setGeometry(QtCore.QRect(30, 330, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btn_encrypt = QtWidgets.QPushButton(CaesarCipher)
        self.btn_encrypt.setGeometry(QtCore.QRect(140, 420, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_encrypt.setFont(font)
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(CaesarCipher)
        self.btn_decrypt.setGeometry(QtCore.QRect(400, 420, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_decrypt.setFont(font)
        self.btn_decrypt.setObjectName("btn_decrypt")

        self.retranslateUi(CaesarCipher)
        QtCore.QMetaObject.connectSlotsByName(CaesarCipher)

    def retranslateUi(self, CaesarCipher):
        _translate = QtCore.QCoreApplication.translate
        CaesarCipher.setWindowTitle(_translate("CaesarCipher", "Dialog"))
        self.label.setText(_translate("CaesarCipher", "CAESAR CIPHER"))
        self.label_2.setText(_translate("CaesarCipher", "Plain Text:"))
        self.label_3.setText(_translate("CaesarCipher", "Key:"))
        self.label_4.setText(_translate("CaesarCipher", "Cipher Text:"))
        self.btn_encrypt.setText(_translate("CaesarCipher", "Encrypt"))
        self.btn_decrypt.setText(_translate("CaesarCipher", "Decrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CaesarCipher = QtWidgets.QDialog()
    ui = Ui_CaesarCipher()
    ui.setupUi(CaesarCipher)
    CaesarCipher.show()
    sys.exit(app.exec_())
